### ISSUE TITLE
download netcdf datasets onto staging server

### ISSUE THREAD

**Issue by ricardogsilva** [geobeyond/Arpav-PPCV-backend#113]
Use the command:

```
arpav-ppcv dev import-thredds-datasets \
    https://thredds.arpa.veneto.it/thredds \
    /home/appuser/data/datasets/ \
    --name-filter={filter}

```

patterns to use in the `filter` parameter:

- [x] `30yr` (720 datasets, ~181 MB)
- [x] `seasonal_anomaly` (192 datasets) - found some errors in the THREDDS URL (see #118)
- [x] `annual` (336 datasets ~13.7 GB)
- [x] `tas_seasonal_absolute` (96 datasets ~9 GB)
- [x] `pr_seasonal_absolute` (96 datasets) - found some errors in the THREDDS URL (see #118)
- [x] `tasmax` (264 datasets ~9 GB) - found some errors in the THREDDS URL (see #118)
- [x] `tasmin` (264 datasets ~9 GB)
- [x] `tas` (888 datasets)
- [x] `pr_` (360 datasets)
- [x] `fd_` (60 datasets)
- [x] `tr_` (60 datasets)
- [x] `su30_` (60 datasets)
- [x] `snwdays_` (60 datasets)
- [x] no `--name-filter` parameter (1488 datasets)
